project:
  type: website
  output-dir: docs

website:
  favicon: images/ZoeUBC.jpeg
  title: "Zoe Horlick"
  navbar:
    background: primary
    search: true
    logo: images/ZoeUBC.jpeg
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: index.qmd
        text: " "
        icon: house-door-fill
      - courses.qmd
      - sidebar:projects

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

